export const tracks = [
  { name: "AI Engineering", roles: ["AI Engineer", "Generative AI Engineer", "LLM Engineer", "AI Application Engineer", "Machine Learning Engineer", "AI Agent Engineer", "RAG Engineer", "AI Evaluation Engineer"], description: "Design, build, and evaluate AI applications that work inside real enterprise systems.", responsibilities: ["Build AI-powered applications and workflows", "Integrate models, data, APIs, and tools", "Evaluate quality, safety, and performance"], backgrounds: ["Software Engineer", "Data Engineer", "Cloud Engineer"], skills: ["Python & APIs", "Application design", "Testing & deployment"], concepts: ["LLMs", "RAG & embeddings", "Agents & evaluation"], project: "AI Banking Knowledge Assistant", technical: 5, business: 3, deliverables: ["Working AI application", "Architecture diagram", "Evaluation report"] },
  { name: "Architecture", roles: ["AI Architect", "AI Solution Architect", "Enterprise AI Architect", "AI Platform Architect", "AI Solutions Engineer"], description: "Translate enterprise needs into secure, scalable AI systems and platforms.", responsibilities: ["Design enterprise AI architectures", "Choose models, data patterns, and integrations", "Plan security, governance, and scale"], backgrounds: ["Solution Architect", "Cloud Engineer", "Data Engineer"], skills: ["Solution design", "Cloud platforms", "Security & integration"], concepts: ["RAG architectures", "Model selection", "Monitoring & governance"], project: "Healthcare Operations Assistant", technical: 4, business: 4, deliverables: ["Solution blueprint", "Architecture diagram", "Implementation roadmap"] },
  { name: "Product / Delivery", roles: ["AI Product Manager", "AI Technical Product Manager", "AI Project Manager", "AI Program Manager", "AI Delivery Manager"], description: "Lead AI opportunities from discovery through delivery, adoption, and measurable value.", responsibilities: ["Prioritize AI use cases and requirements", "Coordinate delivery and stakeholders", "Define success metrics, risks, and ROI"], backgrounds: ["Product Manager", "Project Manager", "Banking Professional"], skills: ["Discovery & roadmapping", "Stakeholder management", "Value measurement"], concepts: ["AI capabilities & limits", "Evaluation", "Responsible AI"], project: "AI Claims Intelligence Workflow", technical: 2, business: 5, deliverables: ["Product brief", "Business case", "Delivery plan"] },
  { name: "Consulting / Transformation", roles: ["AI Consultant", "AI Strategy Consultant", "AI Transformation Consultant", "AI Implementation Consultant", "AI Business Analyst"], description: "Connect industry knowledge to practical AI transformation opportunities.", responsibilities: ["Identify and frame high-value use cases", "Map current and future workflows", "Guide implementation and organizational change"], backgrounds: ["Business Analyst", "Healthcare Professional", "Life Sciences Professional"], skills: ["Process analysis", "Use-case discovery", "Change management"], concepts: ["Enterprise AI", "AI workflows", "Evaluation & governance"], project: "Life Sciences Research Knowledge Assistant", technical: 2, business: 5, deliverables: ["Use-case assessment", "Transformation roadmap", "Executive presentation"] },
  { name: "Governance / Risk", roles: ["AI Governance Specialist", "AI Risk Specialist", "AI Compliance Professional", "Responsible AI Professional", "AI Security Professional", "AI Governance Manager"], description: "Help organizations use AI with appropriate oversight, controls, and accountability.", responsibilities: ["Assess AI risks and controls", "Define review and approval processes", "Document compliance and monitoring requirements"], backgrounds: ["Risk Professional", "Compliance Professional", "Insurance Professional"], skills: ["Risk assessment", "Policy design", "Audit & documentation"], concepts: ["Responsible AI", "Model evaluation", "Human-in-the-loop"], project: "Pharma Knowledge & Document Assistant", technical: 2, business: 5, deliverables: ["Risk register", "Governance framework", "Evaluation plan"] },
];

export const careerMap = [
  { from: "Software Engineer", to: ["AI Engineer", "GenAI Engineer", "AI Application Engineer"], bridge: "Add LLM application design, RAG, and evaluation to your software foundations." },
  { from: "Data Engineer", to: ["AI Engineer", "ML Engineer", "AI Platform Engineer"], bridge: "Extend your data pipelines into retrieval, model workflows, and AI platforms." },
  { from: "Cloud Engineer", to: ["AI Platform Engineer", "AI Infrastructure Engineer", "AI Architect"], bridge: "Apply your infrastructure experience to secure, scalable AI systems." },
  { from: "Project Manager", to: ["AI Project Manager", "AI Program Manager", "AI Transformation Lead"], bridge: "Bring delivery discipline to AI implementation and organizational change." },
  { from: "Product Manager", to: ["AI Product Manager", "AI Technical Product Manager", "AI Transformation Manager"], bridge: "Connect product strategy with AI use-case discovery and evaluation." },
  { from: "Solution Architect", to: ["AI Solution Architect", "Enterprise AI Architect", "AI Architect"], bridge: "Evolve existing architecture practice with models, retrieval, governance, and AI operations." },
  { from: "Business Analyst", to: ["AI Business Analyst", "AI Consultant", "AI Transformation Consultant"], bridge: "Use your process expertise to find and shape practical AI opportunities." },
  { from: "Healthcare Professional", to: ["Healthcare AI Product", "Healthcare AI Consultant", "AI Transformation roles"], bridge: "Bring healthcare context to non-diagnostic AI workflows and product decisions." },
  { from: "Banking Professional", to: ["Banking AI Product", "AI Business Analyst", "AI Transformation / AI Program roles"], bridge: "Apply financial-services knowledge to compliant, human-reviewed AI workflows." },
  { from: "Life Sciences Professional", to: ["Life Sciences AI Product", "AI Consultant", "AI Transformation roles"], bridge: "Turn research and operational expertise into AI knowledge and document solutions." },
];

export const industries = [
  { name: "Banking & Financial Services", short: "Banking", projects: [
    { title: "AI Banking Knowledge Assistant", problem: "Teams spend time searching simulated policies, product documents, SOPs, internal knowledge, and service guidance.", solution: "A permission-aware assistant retrieves approved answers with citations and evaluates response quality.", architecture: "Document ingestion → semantic index → RAG retrieval → access control → cited answer → evaluation", technologies: ["LLMs", "RAG", "Semantic search", "Access control", "Evaluation"], value: "Faster access to approved knowledge with traceable responses.", roles: ["AI Engineer", "AI Architect", "AI Product Manager", "AI Project Manager"] },
    { title: "AI Customer Service Agent", problem: "Customer requests require accurate information, tool actions, context, and careful escalation.", solution: "An agent retrieves approved guidance, calls enterprise tools, logs actions, and routes complex cases to people.", architecture: "Request → intent → retrieval → tool call → response → human escalation → action log", technologies: ["LLMs", "RAG", "Agents", "Tool calling", "Evaluation", "Human-in-the-loop"], value: "More consistent service while keeping people in control.", roles: ["AI Agent Engineer", "AI Architect", "AI Delivery Manager"] },
    { title: "Financial Document Intelligence", problem: "Financial documents arrive in varied formats and need careful review.", solution: "Classify, extract, validate, and summarize documents before human review.", architecture: "Documents → classification → extraction → validation → summarization → human review", technologies: ["Document AI", "LLMs", "Workflow automation", "Validation"], value: "Less manual handling and clearer review trails.", roles: ["AI Engineer", "AI Business Analyst", "AI Product Manager"] },
  ] },
  { name: "Healthcare", short: "Healthcare", projects: [
    { title: "Healthcare Knowledge Assistant", problem: "Simulated clinical guidelines, hospital policies, medical documentation, and procedures are spread across sources.", solution: "Retrieve relevant passages with source citations, evaluation, and access controls.", architecture: "Approved documents → ingestion → retrieval → cited response → evaluation", technologies: ["RAG", "Document retrieval", "Citations", "Evaluation", "Access control"], value: "Traceable access to educational knowledge sources.", roles: ["AI Engineer", "Healthcare AI Consultant", "AI Governance Specialist"], note: "Educational simulation — not a medical diagnostic system." },
    { title: "Healthcare Document Intelligence", problem: "Medical documents need structured information and accountable review.", solution: "Classify, extract, summarize, validate, and send outputs to human reviewers.", architecture: "Medical documents → classification → extraction → summarization → validation → human review", technologies: ["Document AI", "LLMs", "RAG", "Workflow automation", "Human-in-the-loop"], value: "A clearer, reviewable document workflow.", roles: ["AI Engineer", "Healthcare AI Product", "AI Business Analyst"], note: "Educational simulation — not a medical diagnostic system." },
    { title: "Healthcare Operations Assistant", problem: "Operational teams search across policies, procedures, scheduling, and administrative information.", solution: "A non-diagnostic assistant supports lookup, internal retrieval, and document summaries.", architecture: "Question → policy retrieval → approved tool → cited summary → governance review", technologies: ["AI architecture", "RAG", "Agents", "Enterprise integration", "Governance"], value: "Faster administrative knowledge access.", roles: ["AI Architect", "Healthcare AI Consultant", "AI Project Manager"], note: "Educational simulation — not a medical diagnostic system." },
  ] },
  { name: "Life Sciences", short: "Life Sciences", projects: [
    { title: "Life Sciences Research Knowledge Assistant", problem: "Simulated publications, studies, protocols, and internal research knowledge are hard to navigate.", solution: "Ingest sources, search semantically, generate citations, verify sources, and evaluate answers.", architecture: "Research documents → ingestion → semantic search → RAG → citations → verification", technologies: ["Semantic search", "RAG", "Citations", "Source verification", "Evaluation"], value: "More navigable, verifiable research knowledge.", roles: ["RAG Engineer", "AI Consultant", "Life Sciences AI Product"] },
    { title: "Clinical Research Document Intelligence", problem: "Research documentation requires extraction and validation across multiple formats.", solution: "Create an educational, human-reviewed document processing workflow.", architecture: "Research documents → classification → extraction → summarization → validation → human review", technologies: ["Document AI", "LLM workflows", "RAG", "Evaluation", "Governance"], value: "Structured review with visible oversight.", roles: ["AI Engineer", "AI Business Analyst", "AI Governance Specialist"] },
    { title: "Life Sciences Knowledge Agent", problem: "Research teams need dependable answers from approved sources and tools.", solution: "An agent searches, summarizes, calls approved tools, preserves traceability, and escalates low-confidence results.", architecture: "Query → approved sources → tool calls → traceable summary → confidence check → escalation", technologies: ["Agents", "Tool calling", "RAG", "Traceability", "Evaluation"], value: "Research support with evidence and escalation built in.", roles: ["AI Agent Engineer", "AI Architect", "AI Consultant"] },
  ] },
  { name: "Pharmaceutical", short: "Pharma", projects: [
    { title: "Pharma Knowledge & Document Assistant", problem: "Simulated drug information, SOPs, regulatory records, research, and procedures need careful interpretation.", solution: "Process documents into a cited, human-validated knowledge workflow.", architecture: "Documents → processing → knowledge extraction → RAG → AI response → citation → human validation", technologies: ["RAG", "Document AI", "Citations", "Human validation"], value: "Traceable knowledge workflows with human oversight.", roles: ["AI Engineer", "AI Governance Manager", "AI Consultant"], note: "AI-assisted knowledge workflows, not autonomous medical decision-making." },
  ] },
  { name: "Insurance", short: "Insurance", projects: [
    { title: "AI Claims Intelligence Workflow", problem: "Claims involve varied documents, policy references, and decisions needing human approval.", solution: "Classify, extract, validate, retrieve policy, and prepare analysis for a reviewer.", architecture: "Claim documents → classification → extraction → validation → policy retrieval → AI-assisted analysis → human approval", technologies: ["RAG", "Document AI", "Agent workflows", "Business rules", "Human-in-the-loop", "Evaluation"], value: "More structured claims review without automating approval.", roles: ["AI Product Manager", "AI Business Analyst", "AI Risk Specialist"] },
  ] },
  { name: "Enterprise / IT Services", short: "Enterprise IT", projects: [
    { title: "AI Enterprise Service Desk Agent", problem: "Service tickets require intent recognition, approved knowledge, tools, and oversight.", solution: "Suggest resolutions and tool actions for human approval before ticket updates.", architecture: "Ticket → intent detection → knowledge retrieval → tool call → suggested resolution → human approval → ticket update", technologies: ["AI agents", "Tool calling", "RAG", "Workflow orchestration", "Evaluation", "Monitoring"], value: "More consistent service resolution with accountable actions.", roles: ["AI Agent Engineer", "AI Architect", "AI Delivery Manager"] },
  ] },
];

export const weeks = [
  { title: "AI & Career Transformation", topics: ["AI ecosystem", "AI vs ML vs GenAI", "LLM fundamentals", "Enterprise AI", "AI career landscape", "AI roles", "AI project lifecycle"], deliverable: "Personal AI Career Transition Map" },
  { title: "AI Engineering Foundations", topics: ["LLM architecture", "Tokens", "Embeddings", "Transformers", "APIs", "Models", "AI application architecture"], deliverable: "Enterprise AI Architecture" },
  { title: "Enterprise LLM Applications", topics: ["Prompt engineering", "Structured outputs", "Embeddings", "Vector databases", "RAG", "Knowledge retrieval", "Evaluation"], deliverable: "Enterprise RAG Project" },
  { title: "AI Agents", topics: ["Agent architecture", "Tool calling", "Function calling", "Planning", "Memory", "Agent workflows", "Human-in-the-loop"], deliverable: "Industry AI Agent" },
  { title: "Industry Project", topics: ["Banking", "Healthcare", "Life Sciences", "Pharma", "Insurance", "Enterprise IT"], deliverable: "Industry-specific AI solution" },
  { title: "AI Architecture & Production", topics: ["Architecture", "Model selection", "Data pipelines", "APIs", "Evaluation", "Monitoring", "Scalability", "Cost", "Security", "Governance"], deliverable: "Production-Oriented AI Architecture" },
  { title: "AI Product, Project & Program Management", topics: ["Use-case discovery", "Requirements", "AI product lifecycle", "Project planning", "Program management", "Stakeholders", "Risk", "Governance", "ROI", "Implementation roadmap"], deliverable: "Enterprise AI Implementation Plan" },
  { title: "Capstone & Professional Portfolio", topics: ["Industry AI project", "Architecture diagram", "Business case", "Technical documentation", "AI implementation roadmap", "Executive presentation"], deliverable: "AI Professional Portfolio" },
];
